import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/nav-bar";
import Profile from "./ui/profile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="w-screen h-screen flex">
					<NavBar />
					<div className="grow p-5">
						<Profile />
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
