import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/nav-bar";
import Profile from "./ui/profile/profile";
import Footer from "./ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="w-screen h-screen flex">
					<NavBar />
					<div className="h-full grow p-5 overflow-y-auto">
						<div className="min-h-full max-w-[975px] w-full mx-auto flex flex-col">
							<Profile />
							<section className="grow h-full">{children}</section>
							<Footer />
						</div>
					</div>
				</div>
				<div id="modal" />
			</body>
		</html>
	);
}
